  # - name: Ensure python-apt
  #   shell: apt-get update && apt-get install -y python-apt rsync

  - name: Install nginx
    apt: pkg=nginx state=present

  - name: Install php
    action: apt pkg={{item}} state=present
    with_items:
      - php5-fpm
      - php5-cli

  - name: Ensure git
    apt: pkg=git state=present

  - name: Clone Pico
    git:
      repo: https://github.com/gilbitron/Pico.git
      dest: /var/skydivejkl
      update: no

  - name: Install aswyg for Pico
    git:
      repo: https://github.com/epeli/pico-aswyg-editor-plugin.git
      dest: /var/skydivejkl/plugins/pico-aswyg-editor-plugin
      update: yes

  - name: Install pico_get_by_filename for Pico
    git:
      repo: https://github.com/james2doyle/pico_get_by_filename.git
      dest: /var/skydivejkl/plugins/pico_get_by_filename


  - name: Ensure www-data can write Pico content
    file: path=/var/skydivejkl/content owner=www-data group=www-data recurse=yes

  - name: nginx config
    copy: src=nginx.conf dest=/etc/nginx/nginx.conf
    notify:
      - restart nginx

  - name: nginx config for Pico
    copy: src=pico_nginx.conf dest=/etc/nginx/sites-enabled/10-pico
    notify:
      - restart nginx

  - name: Copy php.ini for php-fpm
    copy: src=php.ini dest=/etc/php5/fpm/php.ini
    notify:
      - restart php5-fpm

  - name: Copy Pico config
    copy: src=pico_config.php dest=/var/skydivejkl/config.php

  - name: Install skydivejkl.fi Pico theme
    synchronize: src=. dest=/var/skydivejkl/themes/skydivejkl delete=yes

  - name: start nginx
    service: name=nginx state=started

  - name: start php5-fpm
    service: name=php5-fpm state=started

