

- name: Install node.js repository
  apt_repository: repo='ppa:chris-lea/node.js'

- name: Install node.js
  apt: pkg=nodejs state=present

- name: Install build tools for native node modules
  apt: pkg=build-essential state=present

- name: Git clone skydiveweather
  git:
    repo: https://github.com/epeli/skydiveweather.git
    dest: /usr/local/lib/skydiveweather
    update: yes

- name: nginx config for skydiveweather
  copy: src=skydiveweather_nginx.conf dest=/etc/nginx/sites-enabled/10-skydiveweather
  notify:
    - restart nginx

- name: npm install
  command: npm install chdir=/usr/local/lib/skydiveweather

- name: Copy upstart script
  copy: src=skydiveweather.upstart dest=/etc/init/skydiveweather.conf

- name: Copy config
  copy: src=config.json dest=/usr/local/lib/skydiveweather/config.json

- name: start skydiveweather
  service: name=skydiveweather state=started
